### ISSUE TITLE
[BUG]: Wrath Classic - missing embedded library

### ISSUE THREAD

**Issue by Road-block** [HizurosWoWAddOns/QuickRoutes#1]
### WoW client

WoW Classic WotLk

### What happened?

Errors on a missing library.

Essentially QuickRoutes embeds HizurosSharedTools which expects https://github.com/HizurosWoWAddOns/LibColors-1.0 to be available but isn't.

### Lua Error Message?

```lua
..outes/libs/HizurosSharedTools/HizurosSharedTools.lua:10: Cannot find a library instance of \"LibColors-1.0\".",
			["time"] = "2023/04/04 13:35:34",
			["locals"] = "(*temporary) = \"Cannot find a library instance of \"LibColors-1.0\".\"\n",
			["stack"] = "[string \"=[C]\"]: in function `error'\n[string \"@Interface/AddOns/Ace3/LibStub-1.0.2-70000/LibStub.lua\"]:23: in function `LibStub'\n[string \"@Interface/AddOns/QuickRoutes/libs/HizurosSharedTools/HizurosSharedTools.lua\"]:10: in main chunk",
			["session"] = 23916,
			["counter"] = 2
```

**Comment by Road-block** [comment]
A note that adding the missing LibColors-1.0 library to libs and the reference to the .toc file gets rid of the errors.

**Comment by hizuro** [comment]
Oh. Thank you for reporting. Update coming soon. :-)

**Comment by Road-block** [comment]
8.1.16 still errors with this on login. Best I can guess is the loading order in the .toc file is wrong.
HizurosSharedTools.lua is listed before the library in the latest package so it still errors when the client tries to load it.

```toc
libs\LibStub\LibStub.lua
libs\CallbackHandler-1.0\CallbackHandler-1.0.lua
libs\AceGUI-3.0\AceGUI-3.0.xml
libs\AceConfig-3.0\AceConfig-3.0.xml
libs\LibDataBroker-1.1\LibDataBroker-1.1.lua
libs\LibDBIcon-1.0\LibDBIcon-1.0.lua
libs\LibQTip-1.0\LibQTip-1.0.lua
libs\LibColors-1.0\LibColors-1.0.lua
libs\HizurosSharedTools\HizurosSharedTools.lua
```
This library section works for me without error.

**Comment by Road-block** [comment]
Fixed with https://github.com/HizurosWoWAddOns/QuickRoutes/releases/tag/8.1.18-release
